using System.Collections.Generic;

namespace Cotabby.Core.Emoji;

/// <summary>One emoji entry: a name, a unicode glyph, and zero+ search aliases.</summary>
public sealed record EmojiEntry(string Name, string Glyph, string[] Aliases);

/// <summary>
/// Built-in subset of the GitHub emoji catalog. Covers the most-used names from
/// the macOS port's emoji catalog plus the README's call-out examples
/// (<c>:smile</c>, <c>:tada</c>, <c>:+1</c>). Bundled as code so the picker
/// works offline and doesn't ship a 1 MB JSON.
/// </summary>
public static class EmojiCatalog
{
    public static readonly IReadOnlyList<EmojiEntry> All =
    [
        // Faces — smiling
        new("grinning",            "😀", new[] { "grin", "smile_big" }),
        new("smile",               "😄", new[] { "happy", "smiley" }),
        new("smiley",              "😃", new[] { "happy" }),
        new("grin",                "😁", new[] { "grin" }),
        new("laughing",            "😆", new[] { "lol", "rofl" }),
        new("sweat_smile",         "😅", new[] { "phew" }),
        new("rofl",                "🤣", new[] { "rolling_on_floor", "lmao", "lol" }),
        new("joy",                 "😂", new[] { "cry_laugh", "lol" }),
        new("slightly_smiling",    "🙂", new[] { "slight_smile" }),
        new("upside_down",         "🙃", Array.Empty<string>()),
        new("wink",                "😉", new[] { "winking" }),
        new("blush",               "😊", new[] { "smiling" }),
        new("innocent",            "😇", new[] { "halo", "angel" }),

        // Faces — affection
        new("smiling_face_with_3_hearts", "🥰", new[] { "love" }),
        new("heart_eyes",          "😍", new[] { "love" }),
        new("starstruck",          "🤩", Array.Empty<string>()),
        new("kissing_heart",       "😘", new[] { "kiss" }),
        new("kissing",             "😗", Array.Empty<string>()),
        new("kissing_smiling",     "😙", Array.Empty<string>()),
        new("kissing_closed_eyes", "😚", Array.Empty<string>()),
        new("smiling_with_tear",   "🥲", Array.Empty<string>()),

        // Faces — tongue
        new("yum",                 "😋", new[] { "delicious" }),
        new("stuck_out_tongue",    "😛", new[] { "tongue" }),
        new("stuck_out_tongue_winking_eye", "😜", Array.Empty<string>()),
        new("zany",                "🤪", new[] { "crazy" }),
        new("stuck_out_tongue_closed_eyes", "😝", Array.Empty<string>()),
        new("money_mouth",         "🤑", new[] { "money" }),

        // Faces — hand
        new("hugging",             "🤗", new[] { "hug" }),
        new("hand_over_mouth",     "🤭", new[] { "oops" }),
        new("shushing",            "🤫", new[] { "shh", "quiet" }),
        new("thinking",            "🤔", new[] { "hmm" }),

        // Faces — neutral / skeptical
        new("zipper_mouth",        "🤐", Array.Empty<string>()),
        new("raised_eyebrow",      "🤨", new[] { "skeptical" }),
        new("neutral",             "😐", Array.Empty<string>()),
        new("expressionless",      "😑", Array.Empty<string>()),
        new("no_mouth",            "😶", Array.Empty<string>()),
        new("smirk",               "😏", new[] { "smirking" }),
        new("unamused",            "😒", Array.Empty<string>()),
        new("roll_eyes",           "🙄", new[] { "eyeroll" }),
        new("grimacing",           "😬", Array.Empty<string>()),
        new("lying",               "🤥", Array.Empty<string>()),

        // Faces — sleepy / unwell
        new("relieved",            "😌", Array.Empty<string>()),
        new("pensive",             "😔", new[] { "sad", "thoughtful" }),
        new("sleepy",               "😪", new[] { "tired" }),
        new("drooling",            "🤤", Array.Empty<string>()),
        new("sleeping",            "😴", new[] { "zzz", "sleep" }),
        new("mask",                "😷", Array.Empty<string>()),
        new("face_with_thermometer", "🤒", new[] { "sick", "fever" }),
        new("face_with_head_bandage", "🤕", new[] { "hurt", "injured" }),
        new("nauseated",           "🤢", new[] { "sick" }),
        new("vomit",               "🤮", new[] { "puke" }),
        new("sneezing",            "🤧", Array.Empty<string>()),
        new("hot",                 "🥵", Array.Empty<string>()),
        new("cold",                "🥶", Array.Empty<string>()),
        new("woozy",               "🥴", Array.Empty<string>()),
        new("dizzy",               "😵", Array.Empty<string>()),
        new("exploding_head",      "🤯", new[] { "mindblown" }),

        // Faces — hat / costume
        new("cowboy",              "🤠", Array.Empty<string>()),
        new("party",               "🥳", new[] { "celebrate", "partying" }),
        new("disguised",           "🥸", Array.Empty<string>()),
        new("sunglasses",          "😎", new[] { "cool" }),
        new("nerd",                "🤓", Array.Empty<string>()),
        new("monocle",             "🧐", Array.Empty<string>()),

        // Faces — concerned
        new("confused",            "😕", Array.Empty<string>()),
        new("worried",             "😟", Array.Empty<string>()),
        new("slightly_frowning",   "🙁", new[] { "frown" }),
        new("frowning",            "☹️", Array.Empty<string>()),
        new("open_mouth",          "😮", new[] { "wow" }),
        new("hushed",              "😯", Array.Empty<string>()),
        new("astonished",          "😲", new[] { "shock" }),
        new("flushed",             "😳", new[] { "blush_shock" }),
        new("pleading",            "🥺", new[] { "puppy_eyes" }),
        new("frowning_open_mouth", "😦", Array.Empty<string>()),
        new("anguished",           "😧", Array.Empty<string>()),
        new("fearful",             "😨", Array.Empty<string>()),
        new("anxious",             "😰", new[] { "cold_sweat" }),
        new("sad_but_relieved",    "😥", Array.Empty<string>()),
        new("cry",                 "😢", new[] { "crying", "tear" }),
        new("sob",                 "😭", new[] { "crying_loud" }),
        new("scream",              "😱", Array.Empty<string>()),
        new("confounded",          "😖", Array.Empty<string>()),
        new("persevere",           "😣", Array.Empty<string>()),
        new("disappointed",        "😞", Array.Empty<string>()),
        new("sweat",               "😓", Array.Empty<string>()),
        new("weary",               "😩", Array.Empty<string>()),
        new("tired_face",          "😫", Array.Empty<string>()),
        new("yawning",             "🥱", Array.Empty<string>()),
        new("triumph",             "😤", new[] { "huff" }),
        new("rage",                "😡", new[] { "angry_red" }),
        new("angry",               "😠", new[] { "mad" }),
        new("cursing",             "🤬", new[] { "swear", "censored" }),

        // Hands
        new("wave",                "👋", new[] { "hello", "hi", "bye" }),
        new("raised_back_of_hand", "🤚", Array.Empty<string>()),
        new("raised_hand",         "✋", new[] { "stop", "high_five" }),
        new("vulcan",              "🖖", Array.Empty<string>()),
        new("ok_hand",             "👌", new[] { "ok" }),
        new("pinched_fingers",     "🤌", Array.Empty<string>()),
        new("pinching_hand",       "🤏", Array.Empty<string>()),
        new("victory",             "✌️", new[] { "peace" }),
        new("crossed_fingers",     "🤞", new[] { "good_luck" }),
        new("love_you_gesture",    "🤟", Array.Empty<string>()),
        new("metal",               "🤘", new[] { "rock_on", "horns" }),
        new("call_me",             "🤙", Array.Empty<string>()),
        new("point_left",          "👈", Array.Empty<string>()),
        new("point_right",         "👉", Array.Empty<string>()),
        new("point_up_2",          "👆", Array.Empty<string>()),
        new("middle_finger",       "🖕", new[] { "flip", "fu" }),
        new("point_down",          "👇", Array.Empty<string>()),
        new("point_up",            "☝️", Array.Empty<string>()),
        new("+1",                  "👍", new[] { "thumbsup", "thumbs_up", "yes", "yes_please", "yup", "yay" }),
        new("-1",                  "👎", new[] { "thumbsdown", "thumbs_down", "no" }),
        new("fist",                "✊", Array.Empty<string>()),
        new("punch",               "👊", new[] { "fistbump" }),
        new("fist_left",           "🤛", Array.Empty<string>()),
        new("fist_right",          "🤜", Array.Empty<string>()),
        new("clap",                "👏", new[] { "applause" }),
        new("raised_hands",        "🙌", new[] { "praise", "celebrate" }),
        new("open_hands",          "👐", Array.Empty<string>()),
        new("palms_up",            "🤲", Array.Empty<string>()),
        new("handshake",           "🤝", Array.Empty<string>()),
        new("pray",                "🙏", new[] { "please", "thanks", "ty" }),
        new("muscle",              "💪", new[] { "flex" }),

        // Symbols / objects (a small set used in chat)
        new("100",                 "💯", new[] { "perfect", "hundred" }),
        new("fire",                "🔥", new[] { "lit", "hot" }),
        new("heart",               "❤️", new[] { "love" }),
        new("orange_heart",        "🧡", Array.Empty<string>()),
        new("yellow_heart",        "💛", Array.Empty<string>()),
        new("green_heart",         "💚", Array.Empty<string>()),
        new("blue_heart",          "💙", Array.Empty<string>()),
        new("purple_heart",        "💜", Array.Empty<string>()),
        new("black_heart",         "🖤", Array.Empty<string>()),
        new("broken_heart",        "💔", Array.Empty<string>()),
        new("two_hearts",          "💕", Array.Empty<string>()),
        new("sparkling_heart",     "💖", Array.Empty<string>()),
        new("heart_eyes_cat",      "😻", Array.Empty<string>()),
        new("eyes",                "👀", new[] { "look", "watching" }),
        new("brain",               "🧠", Array.Empty<string>()),
        new("rocket",              "🚀", new[] { "ship", "fast" }),
        new("tada",                "🎉", new[] { "party", "celebrate", "yay" }),
        new("confetti",            "🎊", new[] { "party" }),
        new("balloon",             "🎈", Array.Empty<string>()),
        new("sparkles",            "✨", new[] { "shiny" }),
        new("star",                "⭐", new[] { "favorite" }),
        new("star2",               "🌟", Array.Empty<string>()),
        new("zap",                 "⚡", new[] { "lightning", "fast" }),
        new("snowflake",           "❄️", new[] { "cold" }),
        new("sun",                 "☀️", new[] { "sunny" }),
        new("cloud",               "☁️", Array.Empty<string>()),
        new("rainbow",             "🌈", Array.Empty<string>()),
        new("ok",                  "🆗", Array.Empty<string>()),
        new("check",               "✅", new[] { "done", "tick", "yes" }),
        new("x",                   "❌", new[] { "no", "wrong" }),
        new("warning",             "⚠️", new[] { "warn" }),
        new("question",            "❓", Array.Empty<string>()),
        new("exclamation",         "❗", Array.Empty<string>()),
        new("bell",                "🔔", Array.Empty<string>()),
        new("bug",                 "🐛", new[] { "issue" }),
        new("computer",            "💻", new[] { "laptop" }),
        new("desktop",             "🖥️", Array.Empty<string>()),
        new("keyboard",            "⌨️", Array.Empty<string>()),
        new("phone",                "📱", new[] { "mobile" }),
        new("battery",             "🔋", Array.Empty<string>()),
        new("plug",                "🔌", Array.Empty<string>()),
        new("link",                "🔗", Array.Empty<string>()),
        new("hammer",              "🔨", Array.Empty<string>()),
        new("wrench",              "🔧", new[] { "fix" }),
        new("gear",                "⚙️", new[] { "settings" }),
        new("clipboard",           "📋", Array.Empty<string>()),
        new("clock",               "🕐", new[] { "time" }),
        new("hourglass",           "⏳", new[] { "wait" }),
        new("calendar",            "📅", Array.Empty<string>()),
        new("memo",                "📝", new[] { "note" }),
        new("books",               "📚", Array.Empty<string>()),
        new("graduation_cap",      "🎓", new[] { "grad" }),
        new("trophy",              "🏆", new[] { "win" }),
        new("medal",               "🏅", Array.Empty<string>()),
        new("first_place",         "🥇", new[] { "gold" }),
        new("second_place",        "🥈", new[] { "silver" }),
        new("third_place",         "🥉", new[] { "bronze" }),
        new("coffee",              "☕", Array.Empty<string>()),
        new("tea",                 "🍵", Array.Empty<string>()),
        new("beer",                "🍺", Array.Empty<string>()),
        new("wine_glass",          "🍷", new[] { "wine" }),
        new("cake",                "🎂", new[] { "birthday" }),
        new("pizza",               "🍕", Array.Empty<string>()),
        new("hamburger",           "🍔", new[] { "burger" }),
        new("dog",                 "🐶", Array.Empty<string>()),
        new("cat",                 "🐱", Array.Empty<string>()),
        new("monkey",              "🐵", Array.Empty<string>()),
        new("pig",                 "🐷", Array.Empty<string>()),
        new("frog",                "🐸", Array.Empty<string>()),
        new("ghost",               "👻", Array.Empty<string>()),
        new("skull",               "💀", Array.Empty<string>()),
        new("alien",               "👽", Array.Empty<string>()),
        new("robot",                "🤖", new[] { "bot" }),
        new("poop",                "💩", new[] { "shit", "pile_of_poo" }),
        new("crown",               "👑", Array.Empty<string>()),
        new("gift",                "🎁", new[] { "present" }),
    ];
}
